#!/bin/zsh

# ------------------------------------------------------------------------------
# Exports
# ------------------------------------------------------------------------------



# Homebrew Exports
# ------------------------------------------------------------------------------
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin":$PATH



# Herd Exports
# ------------------------------------------------------------------------------

export PATH="/Users/weerd/Library/Application Support/Herd/bin/":$PATH

export PHP_INI_SCAN_DIR="/Users/weerd/Library/Application Support/Herd/config/php/":$PHP_INI_SCAN_DIR


# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/weerd/Library/Application Support/Herd/config/php/82/"


# Herd injected PHP 7.4 configuration.
export HERD_PHP_74_INI_SCAN_DIR="/Users/weerd/Library/Application Support/Herd/config/php/74/"


# Herd injected PHP 8.0 configuration.
export HERD_PHP_80_INI_SCAN_DIR="/Users/weerd/Library/Application Support/Herd/config/php/80/"


# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/weerd/Library/Application Support/Herd/config/php/83/"


# Herd injected PHP 8.1 configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/weerd/Library/Application Support/Herd/config/php/81/"
