#!/usr/bin/env bash

# ------------------------------------------------------------------------------
# Aliases
# ------------------------------------------------------------------------------



# UNIX
# ------------------------------------------------------------------------------

# Use coreutils `ls` if available.
hash gls >/dev/null 2>&1 || alias gls="ls"

# Detect which `ls` flavor is in use.
if gls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

# List files options.
# F = put `/` after folders
# h = byte unit suffixes
alias ls='CLICOLOR_FORCE=1 gls -aFh ${colorflag} --group-directories-first'

# List all files.
alias la="ls -la"



# OS X
# ------------------------------------------------------------------------------

alias desk='cd ~/Desktop'
alias dev='cd ~/Code'
alias hosts='subl /etc/hosts'

alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

alias nodemods='cd /usr/local/lib/node_modules'


# Git
# ------------------------------------------------------------------------------

alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gr="git rm"
alias gs="git status"
alias gco="git checkout"
alias gcm="git checkout master"
alias gpl="git pull"
alias gph="git push"
alias gl="git log --pretty=oneline"



# Misc
# ------------------------------------------------------------------------------

alias homestead='function __homestead() { (cd ~/Code/homestead && vagrant $*); unset -f __homestead; }; __homestead'

alias server='php -S localhost:1982'
