#!/usr/bin/env bash


# ------------------------------------------------------------------------------
# Settings for DoSomething.org
# ------------------------------------------------------------------------------


# VAGRANT
# ------------------------------------------------------------------------------

export DS_VAGRANT_MOUNT_NFS="true"



# Laravel
# ------------------------------------------------------------------------------

alias dshomestead='function __dshomestead() { (cd ~/Code/homestead-dosomething && vagrant $*); unset -f __dshomestead; }; __dshomestead'
